export const goals = [
  {
    _id: 1,
    category: 'Personal',
    name: 'my first goal',
    target: 'reach in 3 months',
    startDate: '2020-11-18',
    endDate: '2020-11-18',
    type:'Habit',
    progress: 2,
    total: 5,
    tags:['active'],
    status:"active",
    subGoals: []
  },
  {
    _id: 2,
    category: 'Personal',
    name: 'my first goal',
    target: 'reach in 3 months',
    startDate: '2020-11-18',
    endDate: '2020-11-18',
    type:'Habit',
    progress: 2,
    total: 5,
    tags:['active'],
    status:"active",
    subGoals: []
  },
  {
    _id: 3,
    category: 'Personal',
    name: 'my first goal',
    target: 'reach in 3 months',
    startDate: '2020-11-18',
    endDate: '2020-11-18',
    type:'Habit',
    progress: 2,
    total: 5,
    tags:['active'],
    status:"active",
    subGoals: []
  },
  {
    _id: 4,
    category: 'Personal',
    name: 'my first goal',
    target: 'reach in 3 months',
    startDate: '2020-11-18',
    endDate: '2020-11-18',
    type:'Goal',
    progress: 2,
    total: 5,
    tags:['active'],
    status:"active",
    subGoals: [
      {
        _id: 16,
        name: 'my first goal',
        target: 'reach in 3 months',
        startDate: '2020-11-18',
        endDate: '2020-11-18',
        status:'done',
        progress: 0,
    total: 1,
      },
      {
        _id: 17,
        name: 'my first goal',
        target: 'reach in 3 months',
        startDate: '2020-11-18',
        endDate: '2020-11-18',
        status:'done',
        progress: 0,
    total: 1,
      },
      {
        _id: 18,
        name: 'my first goal',
        target: 'reach in 3 months',
        startDate: '2020-11-18',
        endDate: '2020-11-18',
        status:'pending',
        progress: 0,
    total: 1,
      },
      {
        _id: 19,
        name: 'my first goal',
        target: 'reach in 3 months',
        startDate: '2020-11-18',
        endDate: '2020-11-18',
        status:'pending',
        progress: 0,
    total: 1,
      },
      {
        _id: 20,
        name: 'my first goal',
        target: 'reach in 3 months',
        startDate: '2020-11-18',
        endDate: '2020-11-18',
        status:'pending',
        progress: 0,
    total: 1,
      }
    ]
  },
  {
    _id: 21,
    category: 'Personal',
    name: 'my first goal',
    target: 'reach in 3 months',
    startDate: '2020-11-18',
    endDate: '2020-11-18',
    type:'Goal',
    progress: 0,
    total: 1,
    tags:['active'],
    status:"active",
    subGoals: []
  },
  {
    _id: 22,
    category: 'Personal',
    name: 'my first goal',
    target: 'reach in 3 months',
    startDate: '2020-11-18',
    endDate: '2020-11-18',
    type:'Habit',
    progress: 2,
    total: 5,
    tags:['active'],
    status:"active",
    subGoals: []
  },
];
