const defaultContactFields = [
  {
    title: "FullName",
    type: "String",
    order: 0,
    isShown: true,
  },
  {
    title: "Email",
    type: "String",
    order: 1,
    isShown: false,
  },
  {
    title: "Phone",
    type: "String",
    order: 3,
    isShown: true,
  },
  {
    title: "Second Phone",
    type: "String",
    order: 3,
    isShown: false,
  },
  {
    title: "Photo",
    type: "String",
    order: 4,
    isShown: false,
  },
  {
    title: "Gender",
    type: "String",
    order: 5,
    isShown: false,
  },
  {
    title: "Address",
    type: "String",
    order: 5,
    isShown: true,
  },
  {
    title: "Social Links",
    type: "Array",
    order: 7,
    isShown: false,
  },
  {
    title: "Status",
    type: "String",
    order: 2,
    isShown: true,
  },
  {
    title: "Note",
    type: "String",
    order: 38,
    isShown: true,
  },
  {
    title: "Dob",
    type: "Date",
    order: 10,
    isShown: false,
  },
  {
    title: "Tag",
    type: "Array",
    order: 11,
    isShown: true,
  },
  {
    title: "Company",
    type: "String",
    order: 12,
    isShown: false,
  },
  {
    title: "Company Phone",
    type: "String",
    order: 13,
    isShown: false,
  },
  {
    title: "Company Email",
    type: "String",
    order: 14,
    isShown: false,
  },
  {
    title: "Company Address",
    type: "Object",
    order: 15,
    isShown: false,
  },
  {
    title: "Type",
    type: "String",
    order: 16,
    isShown: false,
  },
  {
    title: "Position",
    type: "String",
    order: 4,
    isShown: true,
  },
  {
    title: "Files",
    type: "Array",
    order: 18,
    isShown: false,
  },
  {
    title: "Others",
    type: "Array",
    order: 19,
    isShown: false,
  },
  {
    title: "Billing Address",
    type: "Object",
    order: 20,
    isShown: false,
  },
  {
    title: "Payment Methods",
    type: "Array",
    order: 21,
    isShown: false,
  },
  {
    title: "Stripe",
    type: "Object",
    order: 22,
    isShown: false,
  },
  {
    title: "Lead Source",
    type: "Array",
    order: 23,
    isShown: false,
  },
  {
    title: "IsFormer",
    type: "Boolean",
    order: 24,
    isShown: false,
  },
  {
    title: "Role",
    type: "Array",
    order: 25,
    isShown: false,
  },
  {
    title: "Shift",
    type: "Array",
    order: 26,
    isShown: false,
  },
  {
    title: "Salary",
    type: "Number",
    order: 27,
    isShown: false,
  },
  {
    title: "PunchId",
    type: "Number",
    order: 28,
    isShown: false,
  },
  {
    title: "OutletId",
    type: "ObjectId",
    order: 29,
    isShown: false,
  },
  {
    title: "Employee Position",
    type: "ObjectId",
    order: 30,
    isShown: false,
  },
  {
    title: "Punch State",
    type: "Boolean",
    order: 31,
    isShown: false,
  },
  {
    title: "IsAddCalendar",
    type: "Boolean",
    order: 32,
    isShown: false,
  },
  {
    title: "IsInternship",
    type: "Boolean",
    order: 33,
    isShown: false,
  },
  {
    title: "Stage",
    type: "String",
    order: 34,
    isShown: false,
  },
  {
    title: "Weight",
    type: "String",
    order: 35,
    isShown: false,
  },
  {
    title: "Height",
    type: "String",
    order: 36,
    isShown: false,
  },
  {
    title: "Size",
    type: "String",
    order: 37,
    isShown: false,
  },
  {
    title: "Family",
    type: "Array",
    order: 38,
    isShown: false,
  },
];

module.exports = { defaultContactFields };
